test:
  adapter: postgresql
  encoding: unicode
  database: pies_api
  pool: 5
  username: pies_api
  password: hornblower13

development:
  adapter: postgresql
  encoding: unicode
  database: pies_api
  pool: 5
  username: pies_api
  password: hornblower13

production:
  adapter: postgresql
  encoding: unicode
  database: pies_api
  host: localhost
  pool: 5
  username: pies_api
  password: <%= ENV['DATABASE_PASSWORD'] %>